repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.73.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
      files: ^tf/
    - id: terraform_validate
      files: ^tf/
    - id: terraform_checkov
      files: ^tf/
    - id: terraform_tflint
      files: ^tf/
    - id: terraform_tfsec
      files: ^tf/

- repo: local
  hooks:
    - id: terraform-docs-modules
      name: terraform-docs-modules
      entry: terraform-docs .
      language: system
      pass_filenames: false
      always_run: true
      files: ^tf/

    - id: terraform-docs-examples
      name: terraform-docs-examples
      entry: "terraform-docs examples"
      language: system
      pass_filenames: false
      always_run: true
      files: ^tf/
