#!/usr/bin/env just --justfile

# Set the environment (dev or prod)
ENVIRONMENT := "dev"
TERRAFORM_OPTIONS := '-var="environment=' + ENVIRONMENT + '"'

go_init:
    go mod init modules/test

go_update:
  go get -u github.com/gruntwork-io/terratest
  go mod tidy -v -e

# Formatting and Validation
fmt:
    terraform fmt
    terraform validate

# Terraform Plan (without applying)
plan:
    export AWS_REGION=us-east-1
    export AWS_DEFAULT_REGION=us-east-1
    terraform fmt
    terraform validate
    terraform plan -out current.plan -var-file="variables_primary_dev.tfvars" -var="is_active_region=true"

# Apply Terraform Plan
apply:
    export AWS_REGION=us-east-1
    export AWS_DEFAULT_REGION=us-east-1
    terraform apply current.plan -var="is_active_region=true"

plan_apply_backup:
    export AWS_REGION=us-east-2
    export AWS_DEFAULT_REGION=us-east-2
    terraform fmt
    terraform validate
    terraform plan -out current.plan -var-file="variables_primary_dev.tfvars" -var="is_active_region=false"
    terraform apply current.plan -var="is_active_region=false"

# Linting all Terraform files
lint:
    echo "No lint yet"

test:
    terraform test -test-directory=integration

check:
    pre-commit run --all-files

# Run Terratest
terratest:
    go test ./test -v

validate:
    terraform validate

destroy:
    terraform destroy

# Running all commands
all: fmt lint validate plan apply terratest
    @echo "Development steps completed successfully."
