[project]
name = "snapstart-checker"
version = "0.1.0"
description = "Verify if lambdas are configured correctly for snapstart"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.10",
    "moto>=5.1.4",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-mock",
    "moto[server]",
]