---
name: CDK Infra CI

on:
  push:
    paths:
      - 'cdk/**'
  pull_request:
    paths:
      - 'cdk/**'
  workflow_dispatch:  # This enables manual runs from the GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cdk
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install just
        uses: extractions/setup-just@v1

      - name: Install CDK globally (nodejs app)
        run: just init_cdk

      - name: Set up virtual environment and install dependencies
        run: just install

      - name: Run linter
        run: just lint

      - name: Run tests
        run: just test

      - name: Synthesize CDK template
        run: just synth
